framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    # Disable default asset manifest to avoid the missing manifest.json error
    assets:
        packages:
            default:
                base_path: '/assets'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file