# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    course_images_directory: '%kernel.project_dir%/public/uploads/images'
    part_videos_directory: '%kernel.project_dir%/public/uploads/videos'
    python_binary: '%env(PYTHON_BINARY)%'
    quiz_generator_script: '%env(QUIZ_GENERATOR_SCRIPT)%'
    final_quiz_generator_script: '%env(FINAL_QUIZ_GENERATOR_SCRIPT)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\CourseProgressService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Service\QuizService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $logger: '@logger'
            $pythonBinary: '%python_binary%'
            $quizGeneratorScript: '%quiz_generator_script%'
            $finalQuizGeneratorScript: '%final_quiz_generator_script%'

    App\Controller\CourseController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $progressService: '@App\Service\CourseProgressService'
            $quizService: '@App\Service\QuizService'
            $logger: '@logger'

    App\Twig\AppExtension:
        arguments:
            $tokenStorage: '@security.token_storage'
            $entityManager: '@doctrine.orm.entity_manager'
            $quizAttemptRepository: '@App\Repository\QuizAttemptRepository'
        tags: ['twig.extension']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones